import { CaseCategory } from '../models/case-category.enum';
import { CasePriority } from '../models/case-priority.enum';
import { CaseStatus } from '../models/case-status.enum';
import type { ICase } from '../models/case.interface';

const CASES: readonly ICase[] = [
  {
    id: '#12401',
    customer: 'Acme Corporation',
    title: 'Unable to access analytics dashboard',
    category: CaseCategory.TECHNICAL_SUPPORT,
    priority: CasePriority.HIGH,
    status: CaseStatus.IN_PROGRESS,
    sla: '2h 15m',
    assignee: 'Sarah Lee',
    updatedAt: '2025-05-18T10:24:00',
  },
  {
    id: '#12400',
    customer: 'Globex Inc.',
    title: 'Account owner update required',
    category: CaseCategory.ACCOUNT_MANAGEMENT,
    priority: CasePriority.MEDIUM,
    status: CaseStatus.WAITING,
    sla: '5h 40m',
    assignee: 'Michael Chen',
    updatedAt: '2025-05-18T09:15:00',
  },
  {
    id: '#12399',
    customer: 'Soylent Corp.',
    title: 'Billing details mismatch',
    category: CaseCategory.BILLING,
    priority: CasePriority.CRITICAL,
    status: CaseStatus.SLA_RISK,
    sla: '15m',
    assignee: 'Emily Nguyen',
    updatedAt: '2025-05-18T08:47:00',
  },
  {
    id: '#12398',
    customer: 'Initech',
    title: 'New user access request',
    category: CaseCategory.TECHNICAL_SUPPORT,
    priority: CasePriority.LOW,
    status: CaseStatus.NEW,
    sla: '7h 20m',
    assignee: 'David Kim',
    updatedAt: '2025-05-18T07:31:00',
  },
  {
    id: '#12397',
    customer: 'Umbrella Corp.',
    title: 'Security permissions issue',
    category: CaseCategory.SECURITY,
    priority: CasePriority.HIGH,
    status: CaseStatus.IN_PROGRESS,
    sla: '3h 05m',
    assignee: 'Sarah Lee',
    updatedAt: '2025-05-17T16:22:00',
  },
  {
    id: '#12396',
    customer: 'Stark Industries',
    title: 'Feature flag configuration request',
    category: CaseCategory.FEATURE_REQUEST,
    priority: CasePriority.LOW,
    status: CaseStatus.WAITING,
    sla: '1d 2h',
    assignee: 'Michael Chen',
    updatedAt: '2025-05-17T14:11:00',
  },
  {
    id: '#12395',
    customer: 'Wayne Enterprises',
    title: 'SSO login fails for selected users',
    category: CaseCategory.SECURITY,
    priority: CasePriority.CRITICAL,
    status: CaseStatus.SLA_RISK,
    sla: '28m',
    assignee: 'Emily Nguyen',
    updatedAt: '2025-05-17T13:36:00',
  },
  {
    id: '#12394',
    customer: 'Wonka Industries',
    title: 'Missing invoices in billing panel',
    category: CaseCategory.BILLING,
    priority: CasePriority.MEDIUM,
    status: CaseStatus.IN_PROGRESS,
    sla: '4h 10m',
    assignee: 'David Kim',
    updatedAt: '2025-05-17T12:18:00',
  },
  {
    id: '#12393',
    customer: 'Cyberdyne Systems',
    title: 'API integration timeout',
    category: CaseCategory.TECHNICAL_SUPPORT,
    priority: CasePriority.HIGH,
    status: CaseStatus.IN_PROGRESS,
    sla: '1h 05m',
    assignee: 'Sarah Lee',
    updatedAt: '2025-05-17T11:42:00',
  },
  {
    id: '#12392',
    customer: 'Hooli',
    title: 'Customer contact details update',
    category: CaseCategory.ACCOUNT_MANAGEMENT,
    priority: CasePriority.LOW,
    status: CaseStatus.CLOSED,
    sla: 'Resolved',
    assignee: 'Michael Chen',
    updatedAt: '2025-05-17T10:03:00',
  },
  {
    id: '#12391',
    customer: 'Massive Dynamic',
    title: 'Unable to download exported report',
    category: CaseCategory.TECHNICAL_SUPPORT,
    priority: CasePriority.MEDIUM,
    status: CaseStatus.NEW,
    sla: '6h 45m',
    assignee: 'Emily Nguyen',
    updatedAt: '2025-05-16T17:21:00',
  },
  {
    id: '#12390',
    customer: 'Pied Piper',
    title: 'Subscription renewal confirmation',
    category: CaseCategory.ACCOUNT_MANAGEMENT,
    priority: CasePriority.LOW,
    status: CaseStatus.WAITING,
    sla: '1d 5h',
    assignee: 'David Kim',
    updatedAt: '2025-05-16T16:48:00',
  },
  {
    id: '#12389',
    customer: 'Tyrell Corporation',
    title: 'Unauthorized access alert',
    category: CaseCategory.SECURITY,
    priority: CasePriority.CRITICAL,
    status: CaseStatus.SLA_RISK,
    sla: '9m',
    assignee: 'Sarah Lee',
    updatedAt: '2025-05-16T15:55:00',
  },
  {
    id: '#12388',
    customer: 'Oscorp',
    title: 'Payment method verification failed',
    category: CaseCategory.BILLING,
    priority: CasePriority.HIGH,
    status: CaseStatus.IN_PROGRESS,
    sla: '2h 50m',
    assignee: 'Michael Chen',
    updatedAt: '2025-05-16T14:39:00',
  },
  {
    id: '#12387',
    customer: 'Aperture Science',
    title: 'Request for custom dashboard widget',
    category: CaseCategory.FEATURE_REQUEST,
    priority: CasePriority.MEDIUM,
    status: CaseStatus.NEW,
    sla: '8h 15m',
    assignee: 'Emily Nguyen',
    updatedAt: '2025-05-16T13:26:00',
  },
  {
    id: '#12386',
    customer: 'Vandelay Industries',
    title: 'Customer cannot reset password',
    category: CaseCategory.TECHNICAL_SUPPORT,
    priority: CasePriority.MEDIUM,
    status: CaseStatus.WAITING,
    sla: '5h 05m',
    assignee: 'David Kim',
    updatedAt: '2025-05-16T12:12:00',
  },
  {
    id: '#12385',
    customer: 'Monarch Solutions',
    title: 'Incorrect account ownership assignment',
    category: CaseCategory.ACCOUNT_MANAGEMENT,
    priority: CasePriority.HIGH,
    status: CaseStatus.IN_PROGRESS,
    sla: '3h 25m',
    assignee: 'Sarah Lee',
    updatedAt: '2025-05-16T11:37:00',
  },
  {
    id: '#12384',
    customer: 'Nakatomi Trading',
    title: 'Monthly invoice contains duplicate items',
    category: CaseCategory.BILLING,
    priority: CasePriority.MEDIUM,
    status: CaseStatus.CLOSED,
    sla: 'Resolved',
    assignee: 'Michael Chen',
    updatedAt: '2025-05-16T10:44:00',
  },
  {
    id: '#12383',
    customer: 'Blue Sun Corp.',
    title: 'User role synchronization failed',
    category: CaseCategory.SECURITY,
    priority: CasePriority.HIGH,
    status: CaseStatus.WAITING,
    sla: '4h 35m',
    assignee: 'Emily Nguyen',
    updatedAt: '2025-05-15T17:19:00',
  },
  {
    id: '#12382',
    customer: 'Gekko & Co.',
    title: 'Request to add bulk case assignment',
    category: CaseCategory.FEATURE_REQUEST,
    priority: CasePriority.LOW,
    status: CaseStatus.NEW,
    sla: '1d 1h',
    assignee: 'David Kim',
    updatedAt: '2025-05-15T16:03:00',
  },
  {
    id: '#12381',
    customer: 'Oceanic Airlines',
    title: 'Email notifications are not delivered',
    category: CaseCategory.TECHNICAL_SUPPORT,
    priority: CasePriority.HIGH,
    status: CaseStatus.IN_PROGRESS,
    sla: '2h 05m',
    assignee: 'Sarah Lee',
    updatedAt: '2025-05-15T15:27:00',
  },
  {
    id: '#12380',
    customer: 'Prestige Worldwide',
    title: 'Change primary account manager',
    category: CaseCategory.ACCOUNT_MANAGEMENT,
    priority: CasePriority.LOW,
    status: CaseStatus.CLOSED,
    sla: 'Resolved',
    assignee: 'Michael Chen',
    updatedAt: '2025-05-15T14:02:00',
  },
  {
    id: '#12379',
    customer: 'Vehement Capital Partners',
    title: 'Customer portal shows outdated balance',
    category: CaseCategory.BILLING,
    priority: CasePriority.MEDIUM,
    status: CaseStatus.WAITING,
    sla: '6h 30m',
    assignee: 'Emily Nguyen',
    updatedAt: '2025-05-15T13:44:00',
  },
  {
    id: '#12378',
    customer: 'Initrode',
    title: 'Suspicious login detected',
    category: CaseCategory.SECURITY,
    priority: CasePriority.CRITICAL,
    status: CaseStatus.SLA_RISK,
    sla: '21m',
    assignee: 'David Kim',
    updatedAt: '2025-05-15T12:31:00',
  },
  {
    id: '#12377',
    customer: 'Gringotts Bank',
    title: 'Exported CSV has invalid encoding',
    category: CaseCategory.TECHNICAL_SUPPORT,
    priority: CasePriority.MEDIUM,
    status: CaseStatus.NEW,
    sla: '7h 05m',
    assignee: 'Sarah Lee',
    updatedAt: '2025-05-15T11:08:00',
  },
  {
    id: '#12376',
    customer: 'Dunder Mifflin',
    title: 'Add support for custom approval flow',
    category: CaseCategory.FEATURE_REQUEST,
    priority: CasePriority.LOW,
    status: CaseStatus.WAITING,
    sla: '1d 7h',
    assignee: 'Michael Chen',
    updatedAt: '2025-05-14T17:52:00',
  },
  {
    id: '#12375',
    customer: 'Sterling Cooper',
    title: 'Contract renewal data mismatch',
    category: CaseCategory.ACCOUNT_MANAGEMENT,
    priority: CasePriority.MEDIUM,
    status: CaseStatus.IN_PROGRESS,
    sla: '4h 25m',
    assignee: 'Emily Nguyen',
    updatedAt: '2025-05-14T16:36:00',
  },
  {
    id: '#12374',
    customer: 'Black Mesa',
    title: 'Attachment upload fails for PDF files',
    category: CaseCategory.TECHNICAL_SUPPORT,
    priority: CasePriority.HIGH,
    status: CaseStatus.IN_PROGRESS,
    sla: '1h 35m',
    assignee: 'David Kim',
    updatedAt: '2025-05-14T15:15:00',
  },
  {
    id: '#12373',
    customer: 'Octan Corporation',
    title: 'Invoice email template update',
    category: CaseCategory.BILLING,
    priority: CasePriority.LOW,
    status: CaseStatus.CLOSED,
    sla: 'Resolved',
    assignee: 'Sarah Lee',
    updatedAt: '2025-05-14T14:19:00',
  },
  {
    id: '#12372',
    customer: 'LexCorp',
    title: 'Admin role cannot access settings page',
    category: CaseCategory.SECURITY,
    priority: CasePriority.HIGH,
    status: CaseStatus.WAITING,
    sla: '3h 55m',
    assignee: 'Michael Chen',
    updatedAt: '2025-05-14T13:03:00',
  },
  {
    id: '#12371',
    customer: 'Paper Street Soap Co.',
    title: 'Request for advanced SLA reporting',
    category: CaseCategory.FEATURE_REQUEST,
    priority: CasePriority.MEDIUM,
    status: CaseStatus.NEW,
    sla: '9h 10m',
    assignee: 'Emily Nguyen',
    updatedAt: '2025-05-14T11:42:00',
  },
  {
    id: '#12370',
    customer: 'Good Burger',
    title: 'POS integration sends duplicated events',
    category: CaseCategory.TECHNICAL_SUPPORT,
    priority: CasePriority.CRITICAL,
    status: CaseStatus.SLA_RISK,
    sla: '33m',
    assignee: 'David Kim',
    updatedAt: '2025-05-13T17:28:00',
  },
  {
    id: '#12369',
    customer: 'Los Pollos Hermanos',
    title: 'Billing contact change approval',
    category: CaseCategory.ACCOUNT_MANAGEMENT,
    priority: CasePriority.LOW,
    status: CaseStatus.CLOSED,
    sla: 'Resolved',
    assignee: 'Sarah Lee',
    updatedAt: '2025-05-13T16:06:00',
  },
  {
    id: '#12368',
    customer: 'Biffco Enterprises',
    title: 'Customer cannot view archived cases',
    category: CaseCategory.TECHNICAL_SUPPORT,
    priority: CasePriority.MEDIUM,
    status: CaseStatus.WAITING,
    sla: '5h 20m',
    assignee: 'Michael Chen',
    updatedAt: '2025-05-13T14:44:00',
  },
  {
    id: '#12367',
    customer: 'Planet Express',
    title: 'Webhook secret rotation request',
    category: CaseCategory.SECURITY,
    priority: CasePriority.HIGH,
    status: CaseStatus.IN_PROGRESS,
    sla: '2h 40m',
    assignee: 'Emily Nguyen',
    updatedAt: '2025-05-13T13:18:00',
  },
  {
    id: '#12366',
    customer: 'Daily Bugle',
    title: 'Add custom notification preferences',
    category: CaseCategory.FEATURE_REQUEST,
    priority: CasePriority.LOW,
    status: CaseStatus.NEW,
    sla: '1d 3h',
    assignee: 'David Kim',
    updatedAt: '2025-05-13T11:57:00',
  },
];

export const CASES_MOCK_DATA: readonly ICase[] = CASES;
